dist: trusty
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
  - secure: Vdwpl9LxvtGB4uBi2I92K8jc+u5FAuKAXTGSIuNyWhTG6jqx5lXZkWIdRXv/Cw6b72UrlG0/Fi3Dv+qks9vzDrwMQzvS3L+J1kqZBerIqFnTmhp+dAgiYGTKYTfSboYHbQ27iVMNnPHYkyGsHQioL1YrQIr3oW5NGoEWqgN98psFOprtyWIH8dDNowMlG64TDlL9sm05/YEaQkUX+oSUadiVlE3LXj5TSc3fQvCcAkWZG9U8EHkRSxBhw0R2ehyA2x/s6/pZK1RebqYFSPha9p2FLPHw5sVeeZJpt6sdQoYCzRe35ejF4poEXqnARaUh6D/TCpy7Skjlz/tvdMU4fxkIIAgDmOGPvbrg53EpaTeOGd2bkTjxEMjyJHZF33deL7kRk3gsW4vvlJB44YH5c2h6pdd2b8P9GWGbbZEWJvcErAnaqHYysbJ/m6QFnYrCeRDsBhAvUOwHmn0CdLmUb7yqDFTQ+n9FrmIXkYEngkvk7UgOGo0JezmsL518sbhRVHwws9918qsy+Veyzpf3IJnoOlM4teMSZtHQyRzIJpGBWksre30V0aVTDNmxOF5xPFDjXVzQ/3nRCGuL9vOkyBE8QUo56Ab0s8k9pTW/1fgV+6AkQ+tYTuvF/sTdZVdMKD7s3M64PiqP9eJY/SSTC9jtLhPyWFpngC1UfvQqCnQ=
  - secure: ac7no6jGR4r1OTa1HYlkknmblsk+/g5fx6zrSP9wVBvjQF1uX5yngHohbrKfltZRkNcVIa2a18kUCKZ8Z535b1vL1yQyx2hnr9oRk+sZ5+tupWAzaglAO4vp6d2l/JkcFGleHqkisCxHae2ZWNmg5zWRd0z37EYCElTYINMREUK5Cb0LaNFaBmy5D30MeLnr09dv/yRz37ItSkIIi47dyMUA8xRH7nUSWJwEI1hRa9wte8jG1bumnekfZFWZQmNjdx8y3UfpN/18CLnOv+dNxo8OWqTgCfEHzj/mqgFFOXyk4DhRzOaFgqQWmGO8OTk+Uz2UvmH22RgvQ97j16uGyPITYqYiFcJL6ZYAzwsJM/3sh4SgdMPAsVshCW+twH5hMGBDAgYlLJKr6at9r4OqjtBKIH04ErVPrFl53GAiOe0xeKL3+59RgvW5hE0uDXLDT76u2OTkRSm84Ftv7Zx2bmVNiNk2tjSHqWbhugRkoiBM1mYhZRCaxP6E99nghE5dlicDoNUxVzVUng0gBEWqAu/DDfHJJO38Apjg1pZoCcGJY5vq27wpNIPCchm5C5us1Z+BH5z3OobS2NrhtPeaFyFkEywjmjXVB4aByysbg+lEDZaLKwJVmv7x0c8SGcBBdTwuQTMXeZ125QaLmuXuvgWwWZ3skjyD06Tb9QkUSJU=
  - secure: DtQYVTDJ02aFwB/h8Bo0mUrd1o+7FvI7PKob+84pInqX6hExWxdKEL3rM9pgg0LV3QhXY6kgSMRRR+Aoxxd/CdVZjdfeebfVMm6409WdXPBmv2yqCSc1BzUz/G5W/mC5ugVX9Y7oW4MjFw0e4/rcJnFEAeRPuG6hFU2o0T96n6Q2LMggZT4lXsJLoduxTMe4INbpkwHrX5GRLbfS3IGjqIPD8tER9HrtkwLZmKwQT9aQYQxe8Z4L7qBFQ6RIAYXpOwW3nUGAYRwG9e4H0MWQQoHemUOJSkdOVssTkElHKLyUCL+G3ur50trZK2smk2U6ZCCZPuByuAz47aywCIttMdmj02+SVfAmCTTzvzj/th1J2RRatIyzRX1Fg6j3QOxATRLjiEYT9VLaAsYRgMUCpqTcYnQgucEegU0InQ0R4tjYUONaiFwqtEWEiOOVmsHa2O1uqBZGFsujLbP0Ych1BCxzk6GdP/jHTvXZ55otE8uNzcpwvcYo3dIpT8BlYYMhIBTQl5c+djXRLuftsK1rlUUrnro/50C2oEXh46i2qYp6DT7HaHp7+rcfO0FJjxRMMHnLplyutaVwEntUooEE6UUvauKrt5IosWdJX46tges9oZzdvRfZm+u/tQBFM5vuaFbN9d+kgQo+XC1qL9xdfMhEFqWAMWPHxj9CyLjA/2I=
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
